### ISSUE TITLE
Shorten URL

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/tutorials#6]
Tutorial is showing up in the subdomain and in the folder of the url path.

**Comment by Harjot1Singh** [comment]
It's because the Antora module is also called tutorials. Think of a module as the place where it fetches the data from (so it could be other repositories).

If these tutorials so far are desktop-only, and we're planning to move tutorials to respective repos, then it might be worth calling changing the module name to desktop

**Comment by bhajneet** [comment]
If they are moved to respective repos will the sidebar only include the repo the user is looking at or will they still be able to see tutorials for each repo in the sidebar but change the branch/version at the bottom of the sidebar?

**Comment by Harjot1Singh** [comment]
The sidebar will include top level headers for each of the repos, so i believe it is the latter of what you're describing

**Comment by bhajneet** [comment]
So this is resolved by #2
